### ISSUE TITLE
sesheta-srcops GitHub token

### ISSUE THREAD

**Issue by xtuchyna** [AICoE/SrcOpsMetrics#128]
**Describe the bug**
Current GitHub token for sesheta-srcops bot (present in sesheta-srcops secrets on thoth-test-core) cannot be used in any way.

**To Reproduce**
1. `pip install srcopsmetrics`
2. set env. variable `GITHUB_ACCESS_TOKEN` as the current one in thoth-test-core
3. `GITHUB_ACCESS_TOKEN={token} PYTHONPATH=. pipenv run srcopsmetrics/cli.py -cplr thoth-station/performance`
4. see api rate limit error

**Logger**
```srcopsmetrics-workflow-3661164098: Traceback (most recent call last):
srcopsmetrics-workflow-3661164098:   File "srcopsmetrics/cli.py", line 148, in <module>
srcopsmetrics-workflow-3661164098:     cli()
srcopsmetrics-workflow-3661164098:   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 829, in __call__
srcopsmetrics-workflow-3661164098:     return self.main(*args, **kwargs)
srcopsmetrics-workflow-3661164098:   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 782, in main
srcopsmetrics-workflow-3661164098:     rv = self.invoke(ctx)
srcopsmetrics-workflow-3661164098:   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
srcopsmetrics-workflow-3661164098:     return ctx.invoke(self.callback, **ctx.params)
srcopsmetrics-workflow-3661164098:   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 610, in invoke
srcopsmetrics-workflow-3661164098:     return callback(*args, **kwargs)
srcopsmetrics-workflow-3661164098:   File "srcopsmetrics/cli.py", line 109, in cli
srcopsmetrics-workflow-3661164098:     repos = GitHubKnowledge.get_repositories(repository=repository, organization=organization)
srcopsmetrics-workflow-3661164098:   File "/opt/app-root/src/srcopsmetrics/github_knowledge.py", line 80, in get_repositories
srcopsmetrics-workflow-3661164098:     repos.append(gh.get_repo(repository).full_name)
srcopsmetrics-workflow-3661164098:   File "/opt/app-root/lib/python3.6/site-packages/github/MainClass.py", line 325, in get_repo
srcopsmetrics-workflow-3661164098:     "GET", "%s%s" % (url_base, full_name_or_id)
srcopsmetrics-workflow-3661164098:   File "/opt/app-root/lib/python3.6/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
srcopsmetrics-workflow-3661164098:     verb, url, parameters, headers, input, self.__customConnection(url)
srcopsmetrics-workflow-3661164098:   File "/opt/app-root/lib/python3.6/site-packages/github/Requester.py", line 342, in __check
srcopsmetrics-workflow-3661164098:     raise self.__createException(status, responseHeaders, output)
srcopsmetrics-workflow-3661164098: github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for user ID 66362888.", "documentation_url": "https://developer.github.com/v3/#rate-limiting"}```

**Comment by goern** [comment]
I have noticed that the account was flagged (as a spammer) by gitHub, that is resolved. Could you check again?

**Comment by xtuchyna** [comment]
works like a charm now!
